export const mockChannels = [
  {
    id: '19',
    title: 'BEIN SPORTS 4K',
    image: 'uploads/bein4k.png',
    streamname: 'bein4k',
    type: '0',
    vorder: '1',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein1',
    epg: '5'
  },
  {
    id: '20',
    title: 'BEIN SPORTS 1HD',
    image: 'uploads/bein1.png',
    streamname: '1',
    type: '1',
    vorder: '1',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein1',
    epg: '5'
  },
  {
    id: '21',
    title: 'BEIN SPORTS 2HD',
    image: 'uploads/bein2.png',
    streamname: '2',
    type: '1',
    vorder: '2',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein1',
    epg: '6'
  },
  {
    id: '22',
    title: 'BEIN SPORTS 3HD',
    image: 'uploads/bein3.png',
    streamname: '3',
    type: '1',
    vorder: '3',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein1',
    epg: '7'
  },
  {
    id: '23',
    title: 'BEIN SPORTS MAX HD',
    image: 'uploads/max1.png',
    streamname: '4',
    type: '1',
    vorder: '4',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein1',
    epg: '8'
  },
  {
    id: '24',
    title: 'BEIN SPORTS 5HD',
    image: 'uploads/bein5.png',
    streamname: '5',
    type: '1',
    vorder: '5',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein1',
    epg: '9'
  },
  {
    id: '25',
    title: 'OSN MOVIES FIRST',
    image: 'uploads/osnmoviesfirst.png',
    streamname: '6',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Movies',
    color: '#e67300',
    app: 'live',
    epg: '33'
  },
  {
    id: '27',
    title: 'NAT GEO WILD HD',
    image: 'uploads/NatGeoWild.png',
    streamname: '8',
    type: '1',
    vorder: '17',
    enable: '1',
    cat: 'Entertainment',
    color: '#febd23',
    app: 'live',
    epg: '27'
  },
  {
    id: '28',
    title: 'PLANET EARTH HD',
    image: 'uploads/planetearth.png',
    streamname: '5',
    type: '1',
    vorder: '14',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'live',
    epg: '0'
  },
  {
    id: '29',
    title: 'OSN YAHALA AL OULA',
    image: 'uploads/osnyahalao.png',
    streamname: '9',
    type: '1',
    vorder: '13',
    enable: '1',
    cat: 'Entertainment',
    color: '#ff0000',
    app: 'live',
    epg: '26'
  },
  {
    id: '30',
    title: 'DISCOVERY HD',
    image: 'uploads/discoveryhd.png',
    streamname: '10',
    type: '1',
    vorder: '14',
    enable: '1',
    cat: 'Entertainment',
    color: '#2c6eaa',
    app: 'live',
    epg: '41'
  },
  {
    id: '32',
    title: 'ANIMAL PLANET HD',
    image: 'uploads/AnimalPlant.png',
    streamname: '12',
    type: '1',
    vorder: '18',
    enable: '1',
    cat: 'Entertainment',
    color: '#22CA4E',
    app: 'live',
    epg: '29'
  },
  {
    id: '33',
    title: 'TRAVEL CHANNEL',
    image: 'uploads/travel.png',
    streamname: '13',
    type: '1',
    vorder: '19',
    enable: '1',
    cat: 'Entertainment',
    color: '#0CB3E8',
    app: 'live',
    epg: '0'
  },
  {
    id: '34',
    title: 'DISCOVERY SCIENCE HD',
    image: 'uploads/discoverysc.png',
    streamname: '14',
    type: '1',
    vorder: '20',
    enable: '1',
    cat: 'Entertainment',
    color: '#febd23',
    app: 'live',
    epg: '0'
  },
  {
    id: '35',
    title: 'FIX & FOXI',
    image: 'uploads/fix.png',
    streamname: '15',
    type: '1',
    vorder: '22',
    enable: '1',
    cat: 'Kids',
    color: '#ff0000',
    app: 'live',
    epg: '0'
  },
  {
    id: '36',
    title: 'STEREO MUSIC',
    image: 'uploads/stereo.png',
    streamname: '16',
    type: '1',
    vorder: '24',
    enable: '1',
    cat: 'Music',
    color: '#22CA4E',
    app: 'live',
    epg: '0'
  },
  {
    id: '37',
    title: 'DISNEY CHANNEL',
    image: 'uploads/disney.png',
    streamname: '35',
    type: '1',
    vorder: '23',
    enable: '1',
    cat: 'Kids',
    color: '#54bbf5',
    app: 'live2',
    epg: '48'
  },
  {
    id: '38',
    title: 'HISTORY CHANNEL',
    image: 'uploads/history.png',
    streamname: '34',
    type: '1',
    vorder: '21',
    enable: '1',
    cat: 'Entertainment',
    color: '#000000',
    app: 'live2',
    epg: '47'
  },
  {
    id: '39',
    title: 'BEIN SPORTS 6HD',
    image: 'uploads/bein6.png',
    streamname: '6',
    type: '1',
    vorder: '6',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein2',
    epg: '10'
  },
  {
    id: '40',
    title: 'BEIN SPORTS 7HD',
    image: 'uploads/bein7.png',
    streamname: '7',
    type: '1',
    vorder: '7',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein2',
    epg: '11'
  },
  {
    id: '41',
    title: 'BEIN SPORTS 8HD',
    image: 'uploads/bein8.png',
    streamname: '8',
    type: '1',
    vorder: '8',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein2',
    epg: '12'
  },
  {
    id: '42',
    title: 'BEIN SPORTS 9HD',
    image: 'uploads/bein9.png',
    streamname: '9',
    type: '1',
    vorder: '9',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein2',
    epg: '13'
  },
  {
    id: '43',
    title: 'BEIN SPORTS 10HD',
    image: 'uploads/bein10.png',
    streamname: '10',
    type: '1',
    vorder: '10',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein2',
    epg: '14'
  },
  {
    id: '44',
    title: 'OSN MOVIES BOXOFFICE',
    image: 'uploads/osnboxoffice.png',
    streamname: '36',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Movies',
    color: '#663399',
    app: 'live2',
    epg: '0'
  },
  {
    id: '45',
    title: 'AD SPORTS 3',
    image: 'uploads/ads3.png',
    streamname: '21',
    type: '1',
    vorder: '36',
    enable: '1',
    cat: 'Sports',
    color: '#8f8f8f',
    app: 'live2',
    epg: '0'
  },
  {
    id: '46',
    title: 'TLC HD',
    image: 'uploads/tlc.png',
    streamname: '22',
    type: '1',
    vorder: '26',
    enable: '1',
    cat: 'Entertainment',
    color: '#d2d2d2',
    app: 'live2',
    epg: '45'
  },
  {
    id: '47',
    title: 'FOX ACTION MOVIES',
    image: 'uploads/foxaction.png',
    streamname: '23',
    type: '1',
    vorder: '27',
    enable: '1',
    cat: 'Movies',
    color: '#b41f24',
    app: 'live2',
    epg: '0'
  },
  {
    id: '49',
    title: 'FX HD',
    image: 'uploads/fxhd.png',
    streamname: '25',
    type: '1',
    vorder: '27',
    enable: '1',
    cat: 'Movies',
    color: '#618c09',
    app: 'live2',
    epg: '0'
  },
  {
    id: '50',
    title: 'FOX FAMILY MOVIES',
    image: 'uploads/foxfamily.png',
    streamname: '26',
    type: '1',
    vorder: '28',
    enable: '1',
    cat: 'Movies',
    color: '#1f1e1b',
    app: 'live2',
    epg: '0'
  },
  {
    id: '51',
    title: 'MY CINEMA',
    image: 'uploads/mycinema.png',
    streamname: '27',
    type: '1',
    vorder: '137',
    enable: '1',
    cat: 'Movies',
    color: '#1f1e1b',
    app: 'live2',
    epg: '0'
  },
  {
    id: '52',
    title: 'GAME TOON',
    image: 'uploads/gametoon.png',
    streamname: '28',
    type: '1',
    vorder: '39',
    enable: '1',
    cat: 'Entertainment',
    color: '#c7911e',
    app: 'live2',
    epg: '28'
  },
  {
    id: '53',
    title: 'Discovery Family HD',
    image: 'uploads/discoveryfamily.png',
    streamname: '41',
    type: '1',
    vorder: '51',
    enable: '1',
    cat: 'Entertainment',
    color: '#000000',
    app: 'live3',
    epg: '0'
  },
  {
    id: '54',
    title: 'CARTOON NETWORK ARABIA',
    image: 'uploads/cnarabia.png',
    streamname: '74',
    type: '0',
    vorder: '21',
    enable: '1',
    cat: 'Kids',
    color: '#000000',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '55',
    title: 'AD SPORTS 4',
    image: 'uploads/ads4.png',
    streamname: '43',
    type: '1',
    vorder: '37',
    enable: '1',
    cat: 'Sports',
    color: '#8f8f8f',
    app: 'live3',
    epg: '0'
  },
  {
    id: '56',
    title: 'GULLI',
    image: 'uploads/gulli.png',
    streamname: '44',
    type: '1',
    vorder: '78',
    enable: '1',
    cat: 'Kids',
    color: '#f0cfba',
    app: 'live',
    epg: '0'
  },
  {
    id: '57',
    title: 'OSN MOVIES DRAMA',
    image: 'uploads/osnmoviesdrama.png',
    streamname: '49',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Movies',
    color: '#33001a',
    app: 'live3',
    epg: '0'
  },
  {
    id: '58',
    title: 'OSN FIRST HBO',
    image: 'uploads/osnfirsthbo.png',
    streamname: '45',
    type: '1',
    vorder: '60',
    enable: '1',
    cat: 'Entertainment',
    color: '#eab0ee',
    app: 'live3',
    epg: '37'
  },
  {
    id: '60',
    title: 'DISNEY JUNIOR',
    image: 'uploads/disneyjunior.png',
    streamname: '47',
    type: '1',
    vorder: '68',
    enable: '1',
    cat: 'Kids',
    color: '#9ac720',
    app: 'live3',
    epg: '0'
  },
  {
    id: '62',
    title: 'WWE Network',
    image: 'uploads/wwe.png',
    streamname: '50',
    type: '1',
    vorder: '11',
    enable: '1',
    cat: 'Sports',
    color: '#1f1e1b',
    app: 'live3',
    epg: '0'
  },
  {
    id: '63',
    title: 'OSN MOVIES COMEDY',
    image: 'uploads/osnmoviescomedy.png',
    streamname: '33',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Movies',
    color: '#000000',
    app: 'live2',
    epg: '0'
  },
  {
    id: '64',
    title: 'MBC+ VARIETY',
    image: 'uploads/mbcv.png',
    streamname: '96',
    type: '1',
    vorder: '52',
    enable: '1',
    cat: 'Entertainment',
    color: '#e0226c',
    app: 'live',
    epg: '0'
  },
  {
    id: '65',
    title: 'DOCUBOX',
    image: 'uploads/docubox.png',
    streamname: '52',
    type: '1',
    vorder: '17',
    enable: '1',
    cat: 'Entertainment',
    color: '#febd23',
    app: 'live3',
    epg: '18'
  },
  {
    id: '66',
    title: 'STAR WORLD HD',
    image: 'uploads/starworld.png',
    streamname: '54',
    type: '1',
    vorder: '51',
    enable: '1',
    cat: 'Movies',
    color: '#4d2438',
    app: 'live3',
    epg: '20'
  },
  {
    id: '67',
    title: 'DUCK TV HD',
    image: 'uploads/duck.png',
    streamname: '55',
    type: '1',
    vorder: '136',
    enable: '1',
    cat: 'Kids',
    color: '#AB0EC0',
    app: 'live3',
    epg: '23'
  },
  {
    id: '68',
    title: 'STAR MOVIES HD',
    image: 'uploads/starmovies.png',
    streamname: '56',
    type: '1',
    vorder: '63',
    enable: '1',
    cat: 'Movies',
    color: '#009bce',
    app: 'live3',
    epg: '21'
  },
  {
    id: '69',
    title: 'AL-RASHEED',
    image: 'uploads/rasheed.png',
    streamname: 'alrasheed1.stream_360p',
    type: '0',
    vorder: '148',
    enable: '1',
    cat: 'Entertainment',
    color: '#9900cc',
    app: 'nile',
    epg: '0'
  },
  {
    id: '70',
    title: 'Aghani TV',
    image: 'uploads/mtvl.png',
    streamname: 'music-alremas1.stream_360p',
    type: '0',
    vorder: '149',
    enable: '1',
    cat: 'Music',
    color: '#9900cc',
    app: 'nile',
    epg: '0'
  },
  {
    id: '71',
    title: 'ROTANA CLIP',
    image: 'uploads/rotanaclip.png',
    streamname: 'rotanaclip2.stream_360p',
    type: '0',
    vorder: '150',
    enable: '1',
    cat: 'Music',
    color: '#006600',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '72',
    title: 'AL-SHARQIYA',
    image: 'uploads/sharqiya.png',
    streamname: 'al-sharqiya2.stream_360p',
    type: '0',
    vorder: '151',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '73',
    title: 'Al-SUMARIA',
    image: 'uploads/sumaria.png',
    streamname: 'al-sumaria3.stream_360p',
    type: '0',
    vorder: '152',
    enable: '1',
    cat: 'Entertainment',
    color: '#669999',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '74',
    title: 'MBC Bollywood',
    image: 'uploads/dubaione.png',
    streamname: 'dubaione3.stream_360p',
    type: '0',
    vorder: '153',
    enable: '1',
    cat: 'Entertainment',
    color: '#9900cc',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '75',
    title: 'ZEE AFLAM',
    image: 'uploads/zeeaflam.png',
    streamname: 'dubaisport2.stream_360p',
    type: '0',
    vorder: '154',
    enable: '1',
    cat: 'Movies',
    color: '#4d0000',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '76',
    title: 'MBC',
    image: 'uploads/mbc.png',
    streamname: 'mbc1.stream_360p',
    type: '0',
    vorder: '53',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'nile',
    epg: '0'
  },
  {
    id: '77',
    title: 'MBC 2',
    image: 'uploads/mbc2.png',
    streamname: 'mbc2.stream_360p',
    type: '0',
    vorder: '54',
    enable: '1',
    cat: 'Movies',
    color: '#9900cc',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '78',
    title: 'MBC 3',
    image: 'uploads/mbc3.png',
    streamname: 'mbc3.stream_360p',
    type: '0',
    vorder: '55',
    enable: '1',
    cat: 'Kids',
    color: '#006600',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '79',
    title: 'MBC 4',
    image: 'uploads/mbc4.png',
    streamname: 'mbc4-1.stream_360p',
    type: '0',
    vorder: '56',
    enable: '1',
    cat: 'Entertainment',
    color: '#9900cc',
    app: 'nile',
    epg: '0'
  },
  {
    id: '80',
    title: 'MBC ACTION',
    image: 'uploads/mbcaction.png',
    streamname: 'mbcaction2.stream_360p',
    type: '0',
    vorder: '57',
    enable: '1',
    cat: 'Movies',
    color: '#e6b800',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '81',
    title: 'MBC BOLLYWOOD',
    image: 'uploads/mbcbollywood.png',
    streamname: 'mbcbo3.stream_360p',
    type: '0',
    vorder: '58',
    enable: '1',
    cat: 'Movies',
    color: '#9900cc',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '82',
    title: 'MBC DRAMA',
    image: 'uploads/mbcdrama.png',
    streamname: 'mbcmax3.stream_360p',
    type: '0',
    vorder: '59',
    enable: '1',
    cat: 'Movies',
    color: '#9900cc',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '83',
    title: 'ROTANA CINEMA',
    image: 'uploads/rotanacinema.png',
    streamname: 'rotana-cinema2.stream_360p',
    type: '0',
    vorder: '162',
    enable: '1',
    cat: 'Movies',
    color: '#006600',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '85',
    title: 'NAT GEO KIDS',
    image: 'uploads/natgeokids.png',
    streamname: 'spacetoon3.stream_360p',
    type: '0',
    vorder: '17',
    enable: '1',
    cat: 'Kids',
    color: '#9900cc',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '86',
    title: 'MBC+ DRAMA',
    image: 'uploads/mbcdramaplus.png',
    streamname: '18',
    type: '1',
    vorder: '51',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'live',
    epg: '0'
  },
  {
    id: '87',
    title: 'BARAEEM',
    image: 'uploads/baraem.png',
    streamname: '17',
    type: '1',
    vorder: '52',
    enable: '1',
    cat: 'Kids',
    color: '#9c9c9c',
    app: 'live',
    epg: '0'
  },
  {
    id: '89',
    title: 'NAT GEO PEOPLE',
    image: 'uploads/natgeopeople.png',
    streamname: '71',
    type: '1',
    vorder: '17',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'live2',
    epg: '0'
  },
  {
    id: '91',
    title: 'OSN MOVIES ACTION',
    image: 'uploads/osnmact.png',
    streamname: '42',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Movies',
    color: '#9c9c9c',
    app: 'live3',
    epg: '0'
  },
  {
    id: '96',
    title: 'BEIN MOVIES 1 HD',
    image: 'uploads/beinmovies1.png',
    streamname: '87',
    type: '1',
    vorder: '123',
    enable: '1',
    cat: 'Movies',
    color: '#9c9c9c',
    app: 'live2',
    epg: '0'
  },
  {
    id: '97',
    title: 'itv Choice',
    image: 'uploads/itv.png',
    streamname: '78',
    type: '1',
    vorder: '23',
    enable: '1',
    cat: 'Movies',
    color: '#9c9c9c',
    app: 'live',
    epg: '0'
  },
  {
    id: '106',
    title: 'OSN MOVIES THRILLER',
    image: 'uploads/osnmoviesthriller.png',
    streamname: '48',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Movies',
    color: '#9c9c9c',
    app: 'live3',
    epg: '0'
  },
  {
    id: '107',
    title: 'BEIN GOURMET HD',
    image: 'uploads/beingourmet.png',
    streamname: '32',
    type: '1',
    vorder: '54',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'live2',
    epg: '0'
  },
  {
    id: '112',
    title: 'RT ARABIC HD',
    image: 'uploads/rtarabic.png',
    streamname: 'rta',
    type: '0',
    vorder: '93',
    enable: '1',
    cat: 'Entertainment',
    color: '#fff',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '113',
    title: 'AD DRAMA HD',
    image: 'uploads/addrama.png',
    streamname: 'add',
    type: '0',
    vorder: '38',
    enable: '1',
    cat: 'Entertainment',
    color: '#663399',
    app: 'nile',
    epg: '0'
  },
  {
    id: '118',
    title: 'ART Hekayat',
    image: 'uploads/arthikayat.png',
    streamname: '24',
    type: '0',
    vorder: '70',
    enable: '1',
    cat: 'Movies',
    color: '#9c9c9c',
    app: 'live',
    epg: '0'
  },
  {
    id: '119',
    title: 'ART Hekayat 2',
    image: 'uploads/arthikayat2.png',
    streamname: '98',
    type: '0',
    vorder: '70',
    enable: '1',
    cat: 'Movies',
    color: '#9c9c9c',
    app: 'live3',
    epg: '0'
  },
  {
    id: '120',
    title: 'ART Cinema',
    image: 'uploads/artcinema.png',
    streamname: '29',
    type: '1',
    vorder: '70',
    enable: '1',
    cat: 'Movies',
    color: '#9c9c9c',
    app: 'live2',
    epg: '0'
  },
  {
    id: '127',
    title: 'AD NAT GEO HD',
    image: 'uploads/adn.png',
    streamname: 'adn',
    type: '0',
    vorder: '17',
    enable: '1',
    cat: 'Entertainment',
    color: '',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '128',
    title: 'IRAQIA SPORT',
    image: 'uploads/iqs.png',
    streamname: 'iqs',
    type: '0',
    vorder: '106',
    enable: '1',
    cat: 'Sports',
    color: '',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '138',
    title: 'YAS SPORTS',
    image: 'uploads/yas.png',
    streamname: 'yas',
    type: '0',
    vorder: '116',
    enable: '1',
    cat: 'Sports',
    color: '',
    app: 'nile',
    epg: '0'
  },
  {
    id: '144',
    title: 'NAT GEO HD',
    image: 'uploads/natgeo.png',
    streamname: '101',
    type: '1',
    vorder: '17',
    enable: '1',
    cat: 'Entertainment',
    color: '',
    app: 'live3',
    epg: '0'
  },
  {
    id: '145',
    title: 'OSN MOVIES DISNEY',
    image: 'uploads/osnmoviesdisney.png',
    streamname: '100',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Entertainment',
    color: '',
    app: 'live3',
    epg: '0'
  },
  {
    id: '150',
    title: 'OSN LIVING',
    image: 'uploads/osnliving.png',
    streamname: '46',
    type: '1',
    vorder: '60',
    enable: '1',
    cat: 'Entertainment',
    color: '#eab0ee',
    app: 'live3',
    epg: '0'
  },
  {
    id: '151',
    title: 'OSN YAHALA CINEMA HD',
    image: 'uploads/osnyahalacinema.png',
    streamname: '31',
    type: '1',
    vorder: '13',
    enable: '1',
    cat: 'Movies',
    color: '#ff0000',
    app: 'live2',
    epg: '26'
  },
  {
    id: '152',
    title: 'IRAQIA NEWS',
    image: 'uploads/iqn.png',
    streamname: 'iqn',
    type: '0',
    vorder: '13',
    enable: '1',
    cat: 'Entertainment',
    color: '#ff0000',
    app: 'nile',
    epg: '26'
  },
  {
    id: '153',
    title: 'MYHD SPORTS 1',
    image: 'uploads/myhdsport1.png',
    streamname: '106',
    type: '1',
    vorder: '23',
    enable: '1',
    cat: 'Sports',
    color: '#54bbf5',
    app: 'live2',
    epg: '0'
  },
  {
    id: '157',
    title: 'Dijla TV',
    image: 'uploads/dijla.png',
    streamname: 'dij',
    type: '0',
    vorder: '40',
    enable: '1',
    cat: 'Entertainment',
    color: '#663399',
    app: 'live',
    epg: '0'
  },
  {
    id: '158',
    title: 'FATAFEAT',
    image: 'uploads/fatafeat.png',
    streamname: '19',
    type: '1',
    vorder: '24',
    enable: '1',
    cat: 'Entertainment',
    color: '#ff0000',
    app: 'live',
    epg: '0'
  },
  {
    id: '159',
    title: 'SYFY HD',
    image: 'uploads/syfy.png',
    streamname: '53',
    type: '1',
    vorder: '91',
    enable: '1',
    cat: 'Entertainment',
    color: '#ff0000',
    app: 'live3',
    epg: '0'
  },
  {
    id: '160',
    title: 'OSN MOVIES HD',
    image: 'uploads/osnmovies.png',
    streamname: '51',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Movies',
    color: '#eab0ee',
    app: 'live3',
    epg: '0'
  },
  {
    id: '164',
    title: 'AD SPORTS 1',
    image: 'uploads/ads1.png',
    streamname: 'ad1',
    type: '0',
    vorder: '34',
    enable: '1',
    cat: 'Sports',
    color: '#8f8f8f',
    app: 'nile',
    epg: '0'
  },
  {
    id: '171',
    title: 'ALKASS 4 HD',
    image: 'uploads/alkass4.png',
    streamname: 'kass4',
    type: '0',
    vorder: '117',
    enable: '1',
    cat: 'Sports',
    color: '',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '172',
    title: 'ALKASS 2 HD',
    image: 'uploads/alkass2.png',
    streamname: 'kass2',
    type: '0',
    vorder: '116',
    enable: '1',
    cat: 'Sports',
    color: '',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '173',
    title: 'ALKASS 1 HD',
    image: 'uploads/alkass1.png',
    streamname: 'kass1',
    type: '0',
    vorder: '115',
    enable: '1',
    cat: 'Sports',
    color: '',
    app: 'nile',
    epg: '0'
  },
  {
    id: '174',
    title: 'Al-Arabiya',
    image: 'uploads/arabiya.png',
    streamname: 'al-arabiya',
    type: '0',
    vorder: '116',
    enable: '1',
    cat: 'Entertainment',
    color: '',
    app: 'nile',
    epg: '0'
  },
  {
    id: '175',
    title: 'MTV Lebanon',
    image: 'uploads/mtvl.png',
    streamname: 'mtvl',
    type: '0',
    vorder: '116',
    enable: '1',
    cat: 'Entertainment',
    color: '',
    app: 'nile2',
    epg: '0'
  },
  {
    id: '176',
    title: 'Rotana Drama',
    image: 'uploads/rotana.png',
    streamname: 'rotanadrama',
    type: '0',
    vorder: '116',
    enable: '1',
    cat: 'Entertainment',
    color: '',
    app: 'nile3',
    epg: '0'
  },
  {
    id: '177',
    title: 'Cinema',
    image: 'uploads/cinema.png',
    streamname: 'cima',
    type: '0',
    vorder: '134',
    enable: '1',
    cat: 'Movies',
    color: '#8f8f8f',
    app: 'live',
    epg: '0'
  },
  {
    id: '180',
    title: 'DMC Drama',
    image: 'uploads/dmcdrama.png',
    streamname: 'dmcdrama',
    type: '0',
    vorder: '100',
    enable: '1',
    cat: 'Entertainment',
    color: '',
    app: 'live',
    epg: '0'
  },
  {
    id: '181',
    title: 'Abu Dhabi TV',
    image: 'uploads/adtv.png',
    streamname: 'sv1',
    type: '0',
    vorder: '100',
    enable: '1',
    cat: 'Entertainment',
    color: '',
    app: 'live',
    epg: '0'
  },
  {
    id: '182',
    title: 'FOX LIFE HD',
    image: 'uploads/foxlife.png',
    streamname: '97',
    type: '1',
    vorder: '30',
    enable: '1',
    cat: 'Entertainment',
    color: '#000000',
    app: 'live2',
    epg: '0'
  },
  {
    id: '184',
    title: 'FOX REWAYAT HD',
    image: 'uploads/foxr.png',
    streamname: '99',
    type: '1',
    vorder: '31',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'live',
    epg: '0'
  },
  {
    id: '187',
    title: 'FOX CRIME HD',
    image: 'uploads/foxcrime.png',
    streamname: '104',
    type: '1',
    vorder: '32',
    enable: '1',
    cat: 'Entertainment',
    color: '#0CB3E8',
    app: 'live',
    epg: '0'
  },
  {
    id: '188',
    title: 'BEIN DRAMA 1 HD',
    image: 'uploads/beindrama1.png',
    streamname: '103',
    type: '1',
    vorder: '123',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'live2',
    epg: '0'
  },
  {
    id: '189',
    title: 'FOOD NETWORK',
    image: 'uploads/food.png',
    streamname: '105',
    type: '1',
    vorder: '26',
    enable: '1',
    cat: 'Entertainment',
    color: '#d2d2d2',
    app: 'live2',
    epg: '45'
  },
  {
    id: '190',
    title: 'ZEE Alwan',
    image: 'uploads/zeeaflam.png',
    streamname: 'zeealwan',
    type: '0',
    vorder: '154',
    enable: '1',
    cat: 'Movies',
    color: '#4d0000',
    app: 'nile',
    epg: '0'
  },
  {
    id: '195',
    title: 'DMC HD',
    image: 'uploads/dmchd.png',
    streamname: 'dmchd',
    type: '0',
    vorder: '154',
    enable: '1',
    cat: 'Entertainment',
    color: '#4d0000',
    app: 'live3',
    epg: '0'
  },
  {
    id: '200',
    title: 'EURONEWS',
    image: 'uploads/euronews.png',
    streamname: '72',
    type: '1',
    vorder: '190',
    enable: '1',
    cat: 'Entertainment',
    color: '#ffffff',
    app: 'live2',
    epg: '0'
  },
  {
    id: '201',
    title: 'DW ARABIA',
    image: 'uploads/dwarabia.png',
    streamname: '85',
    type: '1',
    vorder: '110',
    enable: '1',
    cat: 'Entertainment',
    color: '#0f0f0f',
    app: 'live3',
    epg: '0'
  },
  {
    id: '202',
    title: 'TV5 Monde Style',
    image: 'uploads/tv5.png',
    streamname: '74',
    type: '1',
    vorder: '110',
    enable: '1',
    cat: 'Entertainment',
    color: '#0f0f0f',
    app: 'live3',
    epg: '0'
  },
  {
    id: '203',
    title: 'FILMBOX',
    image: 'uploads/filmbox.png',
    streamname: '75',
    type: '1',
    vorder: '110',
    enable: '1',
    cat: 'Movies',
    color: '#0f0f0f',
    app: 'live3',
    epg: '0'
  },
  {
    id: '204',
    title: 'STINGRAY iConcerts',
    image: 'uploads/iconcerts.png',
    streamname: '76',
    type: '1',
    vorder: '110',
    enable: '1',
    cat: 'Music',
    color: '#0f0f0f',
    app: 'live3',
    epg: '0'
  },
  {
    id: '205',
    title: 'France 24',
    image: 'uploads/france24.png',
    streamname: '82',
    type: '1',
    vorder: '110',
    enable: '1',
    cat: 'Entertainment',
    color: '#0f0f0f',
    app: 'live3',
    epg: '0'
  },
  {
    id: '206',
    title: 'V HD',
    image: 'uploads/v.png',
    streamname: '84',
    type: '1',
    vorder: '110',
    enable: '1',
    cat: 'Music',
    color: '#0f0f0f',
    app: 'live3',
    epg: '0'
  },
  {
    id: '207',
    title: 'BBC EARTH',
    image: 'uploads/bbcearth.png',
    streamname: '83',
    type: '1',
    vorder: '110',
    enable: '1',
    cat: 'Entertainment',
    color: '#0f0f0f',
    app: 'live3',
    epg: '0'
  },
  {
    id: '208',
    title: 'BEIN SERIES 1 HD',
    image: 'uploads/beinseries1.png',
    streamname: '81',
    type: '1',
    vorder: '123',
    enable: '1',
    cat: 'Entertainment',
    color: '#9c9c9c',
    app: 'live3',
    epg: '0'
  },
  {
    id: '209',
    title: 'OSN MOVIES KIDS',
    image: 'uploads/osnmovieskids.png',
    streamname: '112',
    type: '1',
    vorder: '15',
    enable: '1',
    cat: 'Movies',
    color: '#663399',
    app: 'live',
    epg: '0'
  },
  {
    id: '210',
    title: 'Al-KASS Extra HD',
    image: 'uploads/alkass1.png',
    streamname: 'beinmax',
    type: '1',
    vorder: '5',
    enable: '1',
    cat: 'Sports',
    color: '#663399',
    app: 'bein1',
    epg: '9'
  }
];
